---
# tasks file for frontend% 
- block:
  - name: install haproxy
    package:
      name: haproxy
      state: latest
    become: true
  - name: enable haproxy
    service:
      name: haproxy
      state: started
    become: true
  - name: configure haproxy
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    become: true
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
    become: true
